<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "structured_asset_rendering"
 *
 * Auto generated by Extension Builder 2020-01-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Structured Asset Rendering',
    'description' => 'First try of Content element / content block based TYPO3 CSS and JS rendering.

A Proove of Concept try of the TYPO3 Structured Content Initiative.

Goals
Load only needed CSS
Load only needed JS
Improve page speed
Reduce page resources size
Manage CSS and JS dependencies
Secondary Ideas
Concatenation and compress JS and CSS
Possibility to use SCSS, SASS',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
